In [1]:
import pandas as pd

numcat = pd.read_csv("list_category_img_comma.txt")

In [2]:
numcat

    Number                       Category
0        1    Hooded_Cotton_Canvas_Anorak
1        2                         Blazer
2        3                         Blouse
3        4                         Bomber
4        5                    Button-Down
5        6                       Cardigan
6        7                        Flannel
7        8   Paisley_Print_Strappy_Halter
8        9                         Henley
9       10                         Hoodie
10      11                         Jacket
11      12                         Jersey
12      13                          Parka
13      14        Double-Breasted_Peacoat
14      15                         Poncho
15      16                        Sweater
16      17                           Tank
17      18                            Tee
18      19                            Top
19      20                Knit_Turtleneck
20      21        Drawstring_Cargo_Capris
21      22                         Chinos
22      23                       Culottes
23      24                        Cutoffs
24      25           Frayed_Denim_Gauchos
25      26                          Jeans
26      27                       Jeggings
27      28           Topstitched_Jodhpurs
28      29                        Joggers
29      30                       Leggings
30      31             Water_Print_Sarong
31      32                         Shorts
32      33                          Skirt
33      34                     Sweatpants
34      35                    Sweatshorts
35      36                    Swim_Trunks
36      37   Tile_Print_Drawstring_Caftan
37      38                        (empty)
38      39                           Coat
39      40           Tribal_Print_Coverup
40      41                          Dress
41      42                       Jumpsuit
42      43                         Kaftan
43      44                         Kimono
44      45                        (empty)
45      46       Panda-Hood_Pajama_Onesie
46      47                           Robe
47      48                         Romper

In [5]:
numcat.set_index(['Number'], inplace=True)

In [9]:
numcatdf = pd.DataFrame(numcat)

In [13]:
numcatdf

                             Category
Number
1         Hooded_Cotton_Canvas_Anorak
2                              Blazer
3                              Blouse
4                              Bomber
5                         Button-Down
6                            Cardigan
7                             Flannel
8        Paisley_Print_Strappy_Halter
9                              Henley
10                             Hoodie
11                             Jacket
12                             Jersey
13                              Parka
14            Double-Breasted_Peacoat
15                             Poncho
16                            Sweater
17                               Tank
18                                Tee
19                                Top
20                    Knit_Turtleneck
21            Drawstring_Cargo_Capris
22                             Chinos
23                           Culottes
24                            Cutoffs
25               Frayed_Denim_Gauchos
26                              Jeans
27                           Jeggings
28               Topstitched_Jodhpurs
29                            Joggers
30                           Leggings
31                 Water_Print_Sarong
32                             Shorts
33                              Skirt
34                         Sweatpants
35                        Sweatshorts
36                        Swim_Trunks
37       Tile_Print_Drawstring_Caftan
38                            (empty)
39                               Coat
40               Tribal_Print_Coverup
41                              Dress
42                           Jumpsuit
43                             Kaftan
44                             Kimono
45                            (empty)
46           Panda-Hood_Pajama_Onesie
47                               Robe
48                             Romper

In [16]:
numcatdf.to_csv('numcat.csv')